# Generated by Django 4.1.5 on 2023-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='gluten_free',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
