# Generated by Django 4.1.5 on 2023-01-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_gluten_free_alter_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
